export const PANEL_CREATE_ITEMS = [
  { name: 'Nueva hermandad', typeLabel: 'Entidad', href: '/panel/hermandades/nueva', mark: 'H' },
  { name: 'Nueva imagen', typeLabel: 'Entidad', href: '/panel/imagenes/nueva', mark: 'I' },
  { name: 'Nuevo paso', typeLabel: 'Entidad', href: '/panel/pasos/nuevo', mark: 'P' },
  { name: 'Nueva banda', typeLabel: 'Entidad', href: '/panel/bandas/nueva', mark: 'B' },
  { name: 'Nueva marcha', typeLabel: 'Entidad', href: '/panel/marchas#crear-marcha', mark: '♫' },
  { name: 'Nueva persona', typeLabel: 'Entidad', href: '/panel/agentes/nuevo', mark: 'Pe' },
  { name: 'Nuevo acontecimiento', typeLabel: 'Entidad', href: '/panel/acontecimientos#crear-acontecimiento', mark: 'A' },
  { name: 'Nueva fuente', typeLabel: 'Documentación', href: '/panel/fuentes#crear-fuente', mark: 'F' },
  { name: 'Nueva advocación', typeLabel: 'Dato maestro', href: '/panel/datos/advocaciones#crear-advocacion', mark: 'Ad' },
  { name: 'Nuevo municipio', typeLabel: 'Dato maestro', href: '/panel/datos/municipios#crear-municipio', mark: 'M' },
  { name: 'Nuevo lugar', typeLabel: 'Dato maestro', href: '/panel/datos/lugares#crear-lugar', mark: 'L' },
  { name: 'Nueva curiosidad o dato', typeLabel: 'Editorial', href: '/panel/hoy/banco#crear-contenido', mark: '?' },
]

export const PANEL_CONTEXTUAL_CREATION = [
  { name: 'Titular de Hermandad', parent: 'Hermandad', route: '/panel/hermandades/:id/titulares' },
  { name: 'Paso de Hermandad', parent: 'Hermandad', route: '/panel/hermandades/:id/pasos' },
  { name: 'Salida o procesión', parent: 'Hermandad', route: '/panel/hermandades/:id/salidas' },
  { name: 'Serie anual', parent: 'Hermandad', route: '/panel/hermandades/:id/salidas/recurrentes' },
  { name: 'Culto', parent: 'Hermandad', route: '/panel/hermandades/:id/cultos' },
  { name: 'Hábito', parent: 'Hermandad', route: '/panel/hermandades/:id/habito' },
  { name: 'Pieza patrimonial', parent: 'Hermandad', route: '/panel/hermandades/:id/patrimonio' },
  { name: 'Acompañamiento musical', parent: 'Banda', route: '/panel/bandas/:id/acompanamientos' },
  { name: 'Responsable de Banda', parent: 'Banda', route: '/panel/bandas/:id/direccion' },
  { name: 'Estreno musical', parent: 'Banda', route: '/panel/bandas/:id/estrenos' },
  { name: 'Lanzamiento discográfico', parent: 'Banda', route: '/panel/bandas/:id/discografia' },
  { name: 'Pieza patrimonial de Banda', parent: 'Banda', route: '/panel/bandas/:id/patrimonio' },
  { name: 'Autoría de Imagen', parent: 'Imagen', route: '/panel/imagenes/:id/autorias' },
  { name: 'Intervención de Imagen', parent: 'Imagen', route: '/panel/imagenes/:id/intervenciones' },
  { name: 'Responsable de Paso', parent: 'Paso', route: '/panel/pasos/:id/responsables' },
  { name: 'Fase patrimonial de Paso', parent: 'Paso', route: '/panel/pasos/:id/patrimonio' },
  { name: 'Dedicatoria musical', parent: 'Marcha', route: '/panel/marchas/:id/dedicatorias' },
  { name: 'Grabación musical', parent: 'Marcha', route: '/panel/marchas/:id/grabaciones' },
]
