import test from 'node:test'
import assert from 'node:assert/strict'
import { dashboardFilters, dashboardHref, selectMusicDashboard, accompanimentPosition, isJuvenileAccompaniment, musicDashboardCsv } from '../lib/music-dashboard-capital.js'
const item = (id, scope = 'capital', day = 'Martes Santo', position = 'Tras el paso de palio') => ({ id, scope, day, position, municipality: scope === 'capital' ? 'Sevilla' : 'Dos Hermanas', stepName: 'Paso de palio', brotherhoodName: `Hermandad ${id}` })
const summary = { year: 2027, isAdvance: true, bands: [
 { id: 'a', name: 'Banda A', href: '/bandas/a', typeKey: 'musica', type: 'Banda de música', items: [item('a1'), item('a2','province')], pendingItems: [item('a3')] },
 { id: 'b', name: 'Banda B', href: '/bandas/b', typeKey: 'cornetas', type: 'Cornetas y tambores', items: [item('b1','capital','Viernes de Dolores','Cruz de Guía · sección juvenil'), item('b2','capital','Lunes Santo','Cruz de Guía')], pendingItems: [] },
 { id: 'c', name: 'Banda C', href: '/bandas/c', typeKey: 'capilla', type: 'Música de capilla', items: [{...item('c1'),stepName:'Música en el cortejo',position:'Música en el cortejo'}], pendingItems: [] },
] }
test('capital is the initial scope, while the archived season remains the default', () => { assert.equal(dashboardFilters().scope,'capital'); assert.equal(dashboardFilters().year,2026); assert.equal(dashboardFilters().order,'total') })
test('explicit all, province, legacy empty scope and municipality links remain supported', () => { for (const ambito of ['','todos']) assert.equal(dashboardFilters({ambito}).scope,''); assert.equal(dashboardFilters({ambito:'province'}).scope,'province'); assert.equal(dashboardFilters({municipio:'Dos Hermanas'}).scope,'') })
test('all filter states survive URL round-trip including alphabetical order and pagination', () => { for (const ambito of ['capital','province','todos']) { const f=dashboardFilters({temporada:'2027',ambito,orden:'nombre',jornada:'Martes Santo',posicion:'paso',seccion:'sin-mencion',pagina:'2'}); assert.deepEqual(dashboardFilters(new URL(dashboardHref(f),'https://example.test').searchParams),f) } })
test('invalid additional filters cannot invent a category or day',()=>{ const f=dashboardFilters({jornada:'Concierto',posicion:'palio',seccion:'adultos'}); assert.equal(f.day,'');assert.equal(f.position,'');assert.equal(f.section,'') })
test('capital selection sums the actual items and retains pending outside totals',()=>{ const d=selectMusicDashboard(summary,dashboardFilters({temporada:'2027'}));assert.equal(d.totals.total,4);assert.equal(d.totals.province,0);assert.equal(d.pendingTotal,1);assert.deepEqual(d.positions,{steps:1,guides:2,others:1,juvenile:1});assert.equal(d.byDay.reduce((n,x)=>n+x.count,0),4) })
test('explicit guide position overrides misleading legacy step name',()=>{ assert.equal(accompanimentPosition({position:'Cruz de Guía · sección juvenil',stepName:'Paso de Cristo'}),'guia') })
test('imprecise and explicitly mixed positions are not silently counted as steps',()=>{ assert.equal(accompanimentPosition({position:'Música de capilla',stepName:''}),'otros');assert.equal(accompanimentPosition({position:'Cruz de guía y tras el paso',stepName:''}),'otros') })
test('music in front of a step is still accompaniment of that step',()=>{ assert.equal(accompanimentPosition({position:'Ante el paso del Cristo',stepName:''}),'paso') })
test('juvenile requires an explicit mention, never inferred from guide alone',()=>{ assert.equal(isJuvenileAccompaniment(item('a','capital','Lunes Santo','Cruz de guía')),false);assert.equal(isJuvenileAccompaniment(item('a'),{name:'Agrupación Musical Juvenil'}),true) })
test('day filter drives ranking, pending, totals, histogram and export consistently',()=>{ const f=dashboardFilters({temporada:'2027',jornada:'Martes Santo'}); const d=selectMusicDashboard(summary,f);assert.equal(d.totals.total,2);assert.equal(d.pendingTotal,1);assert.equal(d.bandsCount,2);assert.equal(d.ranking.reduce((n,b)=>n+b.total,0),2);assert.equal(d.histogram.reduce((n,b)=>n+b.count,0),2);assert.equal(musicDashboardCsv(d.rows,2027).trim().split('\r\n').length,3) })
test('position and section combine without double-counting juvenile appearances',()=>{ const d=selectMusicDashboard(summary,dashboardFilters({posicion:'guia',seccion:'juvenil'}));assert.equal(d.totals.total,1);assert.equal(d.positions.juvenile,1);assert.equal(d.positions.guides,1);assert.equal(d.pendingTotal,0) })
test('row position columns reconcile with each total and neither source nor periods mutate',()=>{ const original=JSON.stringify(summary);const d=selectMusicDashboard(summary,dashboardFilters({ambito:'todos'}),1);for(const r of d.rows)assert.equal(r.steps+r.guides+r.others,r.total);assert.equal(d.pageRows.length,1);assert.equal(d.bandsCount,3);assert.equal(JSON.stringify(summary),original) })
