-- Hilo Cofrade · cierre documental de Nuestra Señora de los Reyes · Sastres
-- Corte: 2026-09-05
-- Solo DML editorial. Sin DDL, RLS ni cambios estructurales.

-- Identidad y sede
insert into places (municipality_id,name,slug,place_type,address,notes)
select m.id,'Parroquia de San Ildefonso y Santiago','parroquia-san-ildefonso-santiago-sevilla','Parroquia','Plaza de San Ildefonso, Sevilla','Sede canónica de la Hermandad de los Sastres desde 1840.'
from municipalities m where m.slug='sevilla'
and not exists (select 1 from places where slug='parroquia-san-ildefonso-santiago-sevilla');

update brotherhoods set
 official_name='Primitiva, Real, Muy Antigua y Fervorosa Hermandad de Nuestra Señora de los Reyes, Patrona de los Sastres, San Mateo Apóstol y Evangelista y San Fernando Rey',
 popular_name='Hermandad de los Sastres',
 foundation_text='Existencia documentada en 1252; la tradición corporativa remonta sus orígenes al cerco y conquista de Sevilla por San Fernando.',
 municipality_id=(select id from municipalities where slug='sevilla'),
 canonical_see_place_id=(select id from places where slug='parroquia-san-ildefonso-santiago-sevilla'),
 neighborhood='Centro · San Ildefonso',
 current_procession_day='Último sábado de septiembre',
 history_text='La Hermandad de Nuestra Señora de los Reyes, conocida popularmente como de los Sastres por su histórica vinculación al gremio de maestros sastres o alfayates, conserva noticia fehaciente de su existencia en 1252. Sus orígenes tradicionales se sitúan en tiempos de San Fernando. A comienzos del siglo XVII se estableció en el Convento Casa Grande de San Francisco y, tras la demolición de aquel conjunto, pasó en 1840 a la iglesia de San Ildefonso, su sede actual. La procesión anual de septiembre fue recuperada en 2003 tras un prolongado periodo sin celebrarse.'
where entity_id=(select id from entities where slug='reyes-sastres-sevilla');

update entities set name='Nuestra Señora de los Reyes · Sastres',summary='Primitiva corporación letífica sevillana vinculada históricamente al gremio de sastres. Documentada desde 1252, tiene su sede en San Ildefonso desde 1840 y celebra la procesión de Nuestra Señora de los Reyes el último sábado de septiembre.',updated_at=now() where slug='reyes-sastres-sevilla';

-- Titular
insert into entities (entity_type,name,slug,summary,status)
select 'image','Nuestra Señora de los Reyes, Patrona de los Sastres','nuestra-senora-reyes-sastres-imagen','Imagen mariana sedente y de vestir, de autor desconocido y fechada en el siglo XVI, que reproduce el tipo iconográfico de la Patrona de Sevilla.','published'
where not exists (select 1 from entities where slug='nuestra-senora-reyes-sastres-imagen');
insert into images (entity_id,image_type,execution_date_text,material,description,iconography,is_dress_image,notes)
select id,'Virgen','Siglo XVI','Madera policromada','Imagen sedente de Nuestra Señora de los Reyes, Patrona de los Sastres, de autor desconocido. El Niño Jesús es una imagen barroca posterior, igualmente de autor no documentado.','Virgen sedente como Reina y Trono del Divino Infante',true,'La intervención de 2005 de Almudena Fernández García y José Joaquín Fijo León recuperó una policromía dieciochesca subyacente.' from entities where slug='nuestra-senora-reyes-sastres-imagen'
on conflict (entity_id) do update set execution_date_text=excluded.execution_date_text,description=excluded.description,iconography=excluded.iconography,is_dress_image=excluded.is_dress_image,notes=excluded.notes;
insert into brotherhood_images (brotherhood_entity_id,image_entity_id,relation_type,notes,status)
select h.id,i.id,'Titular','Titular mariana y Patrona de los Sastres.','published' from entities h,entities i where h.slug='reyes-sastres-sevilla' and i.slug='nuestra-senora-reyes-sastres-imagen'
and not exists (select 1 from brotherhood_images x where x.brotherhood_entity_id=h.id and x.image_entity_id=i.id and x.relation_type='Titular');

-- Paso
insert into entities (entity_type,name,slug,summary,status)
select 'step','Paso de tumbilla de Nuestra Señora de los Reyes','paso-tumbilla-reyes-sastres','Paso procesional de tumbilla de Nuestra Señora de los Reyes, inspirado en la disposición tradicional de la Patrona de Sevilla.','published'
where not exists (select 1 from entities where slug='paso-tumbilla-reyes-sastres');
insert into steps (entity_id,step_type,current_condition,description,style,current_state_notes)
select id,'Gloria','preserved','Paso de tumbilla sobre el que procesiona Nuestra Señora de los Reyes. Su techo de tumbilla culminó en 2024 un proceso de bordado diseñado y ejecutado por Manuel Ojeda Rodríguez.','Tumbilla','Configuración vigente documentada en las procesiones de 2024 y 2025.' from entities where slug='paso-tumbilla-reyes-sastres'
on conflict (entity_id) do update set current_condition=excluded.current_condition,description=excluded.description,style=excluded.style,current_state_notes=excluded.current_state_notes;
insert into brotherhood_steps (brotherhood_entity_id,step_entity_id,relation_type,notes,status)
select h.id,s.id,'Paso actual','Paso procesional de la Virgen en la procesión anual de septiembre.','published' from entities h,entities s where h.slug='reyes-sastres-sevilla' and s.slug='paso-tumbilla-reyes-sastres'
and not exists (select 1 from brotherhood_steps x where x.brotherhood_entity_id=h.id and x.step_entity_id=s.id and x.relation_type='Paso actual');
insert into image_steps (image_entity_id,step_entity_id,relation_type,notes,status)
select i.id,s.id,'Procesiona en','Nuestra Señora de los Reyes procesiona en este paso de tumbilla.','published' from entities i,entities s where i.slug='nuestra-senora-reyes-sastres-imagen' and s.slug='paso-tumbilla-reyes-sastres'
and not exists (select 1 from image_steps x where x.image_entity_id=i.id and x.step_entity_id=s.id and x.relation_type='Procesiona en');

-- Cultos recurrentes; no se inventan fechas exactas de septiembre de 2026
insert into cults (brotherhood_entity_id,image_entity_id,cult_type,title,date_rule,month,description,status,is_recurring,recurrence_label,display_order,notes)
select h.id,i.id,'Festividad','Festividad de Nuestra Señora de los Reyes','15 de agosto',8,'Culto en torno a la festividad litúrgica de Nuestra Señora de los Reyes; en 2026 la imagen fue expuesta a la veneración de los fieles en la víspera.','published',true,'Cada 15 de agosto',1,'La forma concreta del culto se determina en la convocatoria anual.' from entities h,entities i where h.slug='reyes-sastres-sevilla' and i.slug='nuestra-senora-reyes-sastres-imagen' and not exists (select 1 from cults c where c.brotherhood_entity_id=h.id and c.title='Festividad de Nuestra Señora de los Reyes');
insert into cults (brotherhood_entity_id,image_entity_id,cult_type,title,date_rule,month,description,status,is_recurring,recurrence_label,display_order,notes)
select h.id,i.id,'Triduo','Solemne Triduo a Nuestra Señora de los Reyes','Fechas según convocatoria anual',9,'Triduo solemne en honor de la titular. En 2024 y 2025 se celebró en septiembre, sin trasladar automáticamente esas fechas a 2026.','published',true,'Anual',2,'No existe aún una ocurrencia exacta de septiembre de 2026.' from entities h,entities i where h.slug='reyes-sastres-sevilla' and i.slug='nuestra-senora-reyes-sastres-imagen' and not exists (select 1 from cults c where c.brotherhood_entity_id=h.id and c.title='Solemne Triduo a Nuestra Señora de los Reyes');
insert into cults (brotherhood_entity_id,image_entity_id,cult_type,title,date_rule,month,description,status,is_recurring,recurrence_label,display_order,notes)
select h.id,i.id,'Función','Función Principal de Instituto','Según convocatoria anual',9,'Función Principal de Instituto de la corporación, ligada en la práctica reciente al ciclo de cultos de septiembre.','published',true,'Anual',3,'La tradición histórica la vinculó también a fechas próximas al 23 de noviembre; no se fija una regla inmutable ante la variación contemporánea.' from entities h,entities i where h.slug='reyes-sastres-sevilla' and i.slug='nuestra-senora-reyes-sastres-imagen' and not exists (select 1 from cults c where c.brotherhood_entity_id=h.id and c.title='Función Principal de Instituto');

-- Salidas
insert into outings (brotherhood_entity_id,outing_type,character,title,outing_date,year,municipality_id,origin_place_id,destination_place_id,reason,description,event_status,status,route_summary,public_notes,origin_text,destination_text)
select h.id,'Gloria','ordinary','Procesión anual de Nuestra Señora de los Reyes',date '2025-09-27',2025,m.id,p.id,p.id,'Procesión anual del último sábado de septiembre','Procesión gloriosa desde San Ildefonso con estaciones en el entorno de San Leandro, Santiago y San Esteban.','held','published','San Ildefonso · Cristo de Burgos · San Leandro · Santiago · San Esteban · San Ildefonso','Última procesión anual con fecha exacta documentada en esta carga. La salida de 2026 no se anticipa hasta convocatoria propia.','Parroquia de San Ildefonso y Santiago','Parroquia de San Ildefonso y Santiago' from entities h,municipalities m,places p where h.slug='reyes-sastres-sevilla' and m.slug='sevilla' and p.slug='parroquia-san-ildefonso-santiago-sevilla' and not exists (select 1 from outings o where o.brotherhood_entity_id=h.id and o.outing_date=date '2025-09-27' and o.title='Procesión anual de Nuestra Señora de los Reyes');
insert into outings (brotherhood_entity_id,outing_type,character,title,year,municipality_id,reason,description,event_status,status,public_notes,origin_text,destination_text)
select h.id,'Extraordinaria','extraordinary','Participación en el Congreso Mariano Nacional de Zaragoza',1954,m.id,'Congreso Mariano Nacional y consagración al Inmaculado Corazón de María','Nuestra Señora de los Reyes de los Sastres fue trasladada a Zaragoza y participó en la procesión mariana del Congreso de 1954.','held','published','Acontecimiento histórico; no debe aparecer como salida futura o anunciada.','Sevilla','Zaragoza' from entities h,municipalities m where h.slug='reyes-sastres-sevilla' and m.slug='sevilla' and not exists (select 1 from outings o where o.brotherhood_entity_id=h.id and o.year=1954 and o.title='Participación en el Congreso Mariano Nacional de Zaragoza');

-- Música: última continuidad documentada, sin marcar 2026 como actual
insert into music_accompaniment_periods (brotherhood_entity_id,band_entity_id,step_entity_id,position,outing_type,year_from,year_to,is_current,notes,status,public_brotherhood_name,public_step_name,public_brotherhood_slug,public_municipality_name,public_municipality_slug,public_province)
select h.id,b.id,s.id,'Tras la Virgen','Gloria',2024,2025,false,'Acompañamiento documentado en las procesiones de 2024 y 2025. No se presenta como vigente para 2026 mientras no exista confirmación específica de la próxima salida.','published','Nuestra Señora de los Reyes · Sastres','Paso de tumbilla de Nuestra Señora de los Reyes','reyes-sastres-sevilla','Sevilla','sevilla','Sevilla' from entities h,entities b,entities s where h.slug='reyes-sastres-sevilla' and b.slug='las-cigarreras' and s.slug='paso-tumbilla-reyes-sastres' and not exists (select 1 from music_accompaniment_periods x where x.brotherhood_entity_id=h.id and x.band_entity_id=b.id and x.year_from=2024 and x.year_to=2025);

-- Patrimonio
insert into entities (entity_type,name,slug,summary,status) select 'heritage_asset','Coronas de Nuestra Señora de los Reyes y el Niño','coronas-reyes-sastres','Conjunto de coronas de plata labrada con pedrería, fechado a finales del siglo XVI.','published' where not exists (select 1 from entities where slug='coronas-reyes-sastres');
insert into heritage_assets (entity_id,parent_entity_id,asset_type,description,date_from_text,is_current,materials,historical_context,display_order,is_featured) select a.id,h.id,'Orfebrería','Coronas de plata labrada a fuego con adornos de pedrería para la Virgen y el Niño.','Finales del siglo XVI',true,'Plata y pedrería','Piezas históricas asociadas al conjunto iconográfico de Nuestra Señora de los Reyes.',1,true from entities a,entities h where a.slug='coronas-reyes-sastres' and h.slug='reyes-sastres-sevilla' on conflict (entity_id) do update set description=excluded.description,date_from_text=excluded.date_from_text,is_current=true,materials=excluded.materials,historical_context=excluded.historical_context;
insert into entities (entity_type,name,slug,summary,status) select 'heritage_asset','Techo bordado de la tumbilla de los Sastres','techo-tumbilla-reyes-sastres','Techo de tumbilla bordado, diseñado y confeccionado por Manuel Ojeda Rodríguez y culminado en 2024.','published' where not exists (select 1 from entities where slug='techo-tumbilla-reyes-sastres');
insert into heritage_assets (entity_id,parent_entity_id,asset_type,description,date_from_text,is_current,technique,historical_context,display_order,is_featured) select a.id,h.id,'Bordado','Techo de tumbilla del paso procesional, completamente bordado tras culminar en 2024 el proceso diseñado y ejecutado por Manuel Ojeda Rodríguez.','Culminado en 2024',true,'Bordado','Estreno patrimonial culminado en la procesión del 28 de septiembre de 2024.',2,true from entities a,entities h where a.slug='techo-tumbilla-reyes-sastres' and h.slug='reyes-sastres-sevilla' on conflict (entity_id) do update set description=excluded.description,date_from_text=excluded.date_from_text,is_current=true,technique=excluded.technique,historical_context=excluded.historical_context;

-- Hitos históricos
insert into entities (entity_type,name,slug,summary,status) select 'event','Primera constancia documental de la Hermandad de los Sastres','sastres-constancia-documental-1252','Constancia documental de la Hermandad en 1252.','published' where not exists (select 1 from entities where slug='sastres-constancia-documental-1252');
insert into events (entity_id,event_type,event_date_text,description,event_category,brotherhood_entity_id,municipality_id,event_status,public_notes) select ev.id,'Hito histórico','1252','La parroquia documenta noticia fehaciente de la existencia de la corporación en 1252, diferenciándola de la tradición que sitúa sus orígenes durante el cerco de Sevilla.','historical',h.id,m.id,'held','Se conserva la distinción entre tradición de origen y evidencia documental.' from entities ev,entities h,municipalities m where ev.slug='sastres-constancia-documental-1252' and h.slug='reyes-sastres-sevilla' and m.slug='sevilla' on conflict (entity_id) do update set event_date_text=excluded.event_date_text,description=excluded.description,brotherhood_entity_id=excluded.brotherhood_entity_id,municipality_id=excluded.municipality_id,event_status='held';
insert into entities (entity_type,name,slug,summary,status) select 'event','Traslado de la Hermandad de los Sastres a San Ildefonso','sastres-san-ildefonso-1840','La Hermandad pasó a la iglesia de San Ildefonso en 1840 tras abandonar el Convento Casa Grande de San Francisco.','published' where not exists (select 1 from entities where slug='sastres-san-ildefonso-1840');
insert into events (entity_id,event_type,event_date_text,place_id,description,event_category,brotherhood_entity_id,municipality_id,event_status) select ev.id,'Cambio de sede','1840',p.id,'Tras la demolición del Convento Casa Grande de San Francisco, la corporación estableció su sede en San Ildefonso, donde permanece.','historical',h.id,m.id,'held' from entities ev,entities h,municipalities m,places p where ev.slug='sastres-san-ildefonso-1840' and h.slug='reyes-sastres-sevilla' and m.slug='sevilla' and p.slug='parroquia-san-ildefonso-santiago-sevilla' on conflict (entity_id) do update set place_id=excluded.place_id,description=excluded.description,brotherhood_entity_id=excluded.brotherhood_entity_id,municipality_id=excluded.municipality_id,event_status='held';
insert into entities (entity_type,name,slug,summary,status) select 'event','Recuperación de la procesión anual de los Sastres','sastres-recuperacion-procesion-2003','La procesión anual de Nuestra Señora de los Reyes fue recuperada en 2003.','published' where not exists (select 1 from entities where slug='sastres-recuperacion-procesion-2003');
insert into events (entity_id,event_type,event_date_text,place_id,description,event_category,brotherhood_entity_id,municipality_id,event_status) select ev.id,'Recuperación de culto externo','2003',p.id,'La Hermandad recuperó en 2003 la procesión de Nuestra Señora de los Reyes después de muchos años sin celebrarse.','historical',h.id,m.id,'held' from entities ev,entities h,municipalities m,places p where ev.slug='sastres-recuperacion-procesion-2003' and h.slug='reyes-sastres-sevilla' and m.slug='sevilla' and p.slug='parroquia-san-ildefonso-santiago-sevilla' on conflict (entity_id) do update set place_id=excluded.place_id,description=excluded.description,brotherhood_entity_id=excluded.brotherhood_entity_id,municipality_id=excluded.municipality_id,event_status='held';
insert into entity_relations (source_entity_id,relation_type,target_entity_id,notes,status) select ev.id,'involves',h.id,'Acontecimiento propio de la Hermandad.','published' from entities ev,entities h where ev.slug in ('sastres-constancia-documental-1252','sastres-san-ildefonso-1840','sastres-recuperacion-procesion-2003') and h.slug='reyes-sastres-sevilla' and not exists (select 1 from entity_relations r where r.source_entity_id=ev.id and r.target_entity_id=h.id and r.relation_type='involves');

-- Fuentes principales
insert into sources (name,url,source_type,author_or_publisher,accessed_at,notes) select 'Hermandad de Nuestra Señora de los Reyes · Parroquia de San Ildefonso','https://parroquiasanildefonso.wordpress.com/nuestra-senora-de-los-reyes/','Web parroquial','Parroquia de San Ildefonso y Santiago',date '2026-09-05','Historia, constancia de 1252 y sede desde 1840.' where not exists (select 1 from sources where url='https://parroquiasanildefonso.wordpress.com/nuestra-senora-de-los-reyes/');
insert into sources (name,url,source_type,author_or_publisher,accessed_at,notes) select 'Saludo de la Hermana Mayor · Hermandad de los Sastres','https://hermandaddelossastres.blogspot.com/p/saludo-del-hermano-mayor.html','Web oficial de la Hermandad','Hermandad de los Sastres',date '2026-09-05','Títulos, origen gremial y procesión del último sábado de septiembre.' where not exists (select 1 from sources where url='https://hermandaddelossastres.blogspot.com/p/saludo-del-hermano-mayor.html');
insert into sources (name,url,source_type,author_or_publisher,accessed_at,notes) select 'Nuestra Señora de los Reyes, Patrona de los Sastres · imagen y paso','https://www.artesacro.org/Noticia/Ver/17370/hoy-salida-procesional-ntra-sra-reyes-patrona-sastres','Prensa cofrade','ArteSacro',date '2026-09-05','Cronología de la imagen, Niño, restauración de 2005 y coronas históricas.' where not exists (select 1 from sources where url='https://www.artesacro.org/Noticia/Ver/17370/hoy-salida-procesional-ntra-sra-reyes-patrona-sastres');
insert into sources (name,url,source_type,author_or_publisher,publication_date,accessed_at,notes) select 'Procesión de Nuestra Señora de los Reyes de los Sastres · 2024','https://www.artesacro.org/Noticia/Ver/157773/virgen-reyes-sastres-realizo-ayer-su-anual-procesion','Prensa cofrade','ArteSacro',date '2024-09-29',date '2026-09-05','Paso de tumbilla, techo bordado, recuperación de 2003 y música 2024.' where not exists (select 1 from sources where url='https://www.artesacro.org/Noticia/Ver/157773/virgen-reyes-sastres-realizo-ayer-su-anual-procesion');
insert into sources (name,url,source_type,author_or_publisher,publication_date,accessed_at,notes) select 'Cultos de Nuestra Señora de los Reyes de los Sastres · 2025','https://www.artesacro.org/Noticia.asp?idreg=163107','Prensa cofrade','ArteSacro',date '2025-09-21',date '2026-09-05','Triduo y Función Principal de Instituto de 2025.' where not exists (select 1 from sources where url='https://www.artesacro.org/Noticia.asp?idreg=163107');
insert into sources (name,url,source_type,author_or_publisher,publication_date,accessed_at,notes) select 'Procesión de los Sastres · 27 de septiembre de 2025','https://cadenaser.com/andalucia/2025/09/26/la-pastora-de-santa-marina-se-corona-este-sabado-en-la-plaza-del-triunfo-radio-sevilla/','Prensa','Radio Sevilla · Cadena SER',date '2025-09-26',date '2026-09-05','Salida, itinerario y Banda de Música de Las Cigarreras en 2025.' where not exists (select 1 from sources where url='https://cadenaser.com/andalucia/2025/09/26/la-pastora-de-santa-marina-se-corona-este-sabado-en-la-plaza-del-triunfo-radio-sevilla/');
insert into sources (name,url,source_type,author_or_publisher,publication_date,accessed_at,notes) select 'Virgen de los Reyes de los Sastres · Congreso Mariano de Zaragoza','https://www.gentedepaz.es/cuando-la-virgen-de-los-reyes-de-los-sastres-salio-en-procesion-por-zaragoza-con-motivo-del-congreso-mariano-nacional/','Prensa cofrade','Gente de Paz',date '2023-08-13',date '2026-09-05','Participación histórica de 1954.' where not exists (select 1 from sources where url='https://www.gentedepaz.es/cuando-la-virgen-de-los-reyes-de-los-sastres-salio-en-procesion-por-zaragoza-con-motivo-del-congreso-mariano-nacional/');
insert into sources (name,url,source_type,author_or_publisher,publication_date,accessed_at,notes) select 'Secuelas iconográficas de la Virgen de los Reyes','https://odisur.es/sevilla/secuelas-iconograficas-de-la-virgen-de-los-reyes-patrona-de-sevilla-y-su-archidiocesis/','Fuente diocesana','Archidiócesis de Sevilla · ODISUR',date '2024-11-25',date '2026-09-05','Tipo iconográfico e identificación histórica de los Sastres.' where not exists (select 1 from sources where url='https://odisur.es/sevilla/secuelas-iconograficas-de-la-virgen-de-los-reyes-patrona-de-sevilla-y-su-archidiocesis/');
insert into sources (name,url,source_type,author_or_publisher,publication_date,accessed_at,notes) select 'Veneración de la Virgen de los Reyes de los Sastres · agosto 2026','https://lacajacofrade.es/agenda-cofrade-sevilla-fin-de-semana-14-15-16-agosto-2026/','Agenda cofrade','La Caja Cofrade',date '2026-08-14',date '2026-09-05','Veneración celebrada en agosto de 2026.' where not exists (select 1 from sources where url='https://lacajacofrade.es/agenda-cofrade-sevilla-fin-de-semana-14-15-16-agosto-2026/');

-- Enlaces contextuales mínimos según regla #589
insert into source_links (source_id,entity_id,scope,notes) select s.id,h.id,'Identidad · historia · sede','Historia institucional y sede canónica.' from sources s,entities h where s.url='https://parroquiasanildefonso.wordpress.com/nuestra-senora-de-los-reyes/' and h.slug='reyes-sastres-sevilla' and not exists (select 1 from source_links x where x.source_id=s.id and x.entity_id=h.id and x.scope='Identidad · historia · sede');
insert into source_links (source_id,entity_id,scope,notes) select s.id,h.id,'Identidad · gremio · procesión recurrente','Fuente oficial corporativa.' from sources s,entities h where s.url='https://hermandaddelossastres.blogspot.com/p/saludo-del-hermano-mayor.html' and h.slug='reyes-sastres-sevilla' and not exists (select 1 from source_links x where x.source_id=s.id and x.entity_id=h.id and x.scope='Identidad · gremio · procesión recurrente');
insert into source_links (source_id,entity_id,scope,notes) select s.id,i.id,'Titular · cronología · restauración','Imagen, Niño y restauración de 2005.' from sources s,entities i where s.url='https://www.artesacro.org/Noticia/Ver/17370/hoy-salida-procesional-ntra-sra-reyes-patrona-sastres' and i.slug='nuestra-senora-reyes-sastres-imagen' and not exists (select 1 from source_links x where x.source_id=s.id and x.entity_id=i.id and x.scope='Titular · cronología · restauración');
insert into source_links (source_id,entity_id,scope,notes) select s.id,e.id,'Paso · configuración vigente','Paso de tumbilla documentado en 2024.' from sources s,entities e where s.url='https://www.artesacro.org/Noticia/Ver/157773/virgen-reyes-sastres-realizo-ayer-su-anual-procesion' and e.slug='paso-tumbilla-reyes-sastres' and not exists (select 1 from source_links x where x.source_id=s.id and x.entity_id=e.id and x.scope='Paso · configuración vigente');
insert into source_links (source_id,cult_id,scope,notes) select s.id,c.id,'Culto · festividad 2026','Veneración celebrada en agosto de 2026.' from sources s,cults c where s.url='https://lacajacofrade.es/agenda-cofrade-sevilla-fin-de-semana-14-15-16-agosto-2026/' and c.brotherhood_entity_id=(select id from entities where slug='reyes-sastres-sevilla') and c.title='Festividad de Nuestra Señora de los Reyes' and not exists (select 1 from source_links x where x.source_id=s.id and x.cult_id=c.id and x.scope='Culto · festividad 2026');
insert into source_links (source_id,cult_id,scope,notes) select s.id,c.id,'Culto · triduo','Triduo documentado en septiembre de 2025.' from sources s,cults c where s.url='https://www.artesacro.org/Noticia.asp?idreg=163107' and c.brotherhood_entity_id=(select id from entities where slug='reyes-sastres-sevilla') and c.title='Solemne Triduo a Nuestra Señora de los Reyes' and not exists (select 1 from source_links x where x.source_id=s.id and x.cult_id=c.id and x.scope='Culto · triduo');
insert into source_links (source_id,cult_id,scope,notes) select s.id,c.id,'Culto · función principal','Función Principal documentada en 2025.' from sources s,cults c where s.url='https://www.artesacro.org/Noticia.asp?idreg=163107' and c.brotherhood_entity_id=(select id from entities where slug='reyes-sastres-sevilla') and c.title='Función Principal de Instituto' and not exists (select 1 from source_links x where x.source_id=s.id and x.cult_id=c.id and x.scope='Culto · función principal');
insert into source_links (source_id,outing_id,scope,notes) select s.id,o.id,'Salida · procesión 2025','Fecha, itinerario y música.' from sources s,outings o where s.url='https://cadenaser.com/andalucia/2025/09/26/la-pastora-de-santa-marina-se-corona-este-sabado-en-la-plaza-del-triunfo-radio-sevilla/' and o.brotherhood_entity_id=(select id from entities where slug='reyes-sastres-sevilla') and o.outing_date=date '2025-09-27' and not exists (select 1 from source_links x where x.source_id=s.id and x.outing_id=o.id and x.scope='Salida · procesión 2025');
insert into source_links (source_id,outing_id,scope,notes) select s.id,o.id,'Salida histórica · Zaragoza 1954','Participación en el Congreso Mariano.' from sources s,outings o where s.url='https://www.gentedepaz.es/cuando-la-virgen-de-los-reyes-de-los-sastres-salio-en-procesion-por-zaragoza-con-motivo-del-congreso-mariano-nacional/' and o.brotherhood_entity_id=(select id from entities where slug='reyes-sastres-sevilla') and o.year=1954 and not exists (select 1 from source_links x where x.source_id=s.id and x.outing_id=o.id and x.scope='Salida histórica · Zaragoza 1954');
insert into source_links (source_id,music_accompaniment_period_id,scope,notes) select s.id,mp.id,'Acompañamiento histórico · 2024-2025','Continuidad documentada; no vigente por inferencia en 2026.' from sources s,music_accompaniment_periods mp where s.url='https://cadenaser.com/andalucia/2025/09/26/la-pastora-de-santa-marina-se-corona-este-sabado-en-la-plaza-del-triunfo-radio-sevilla/' and mp.brotherhood_entity_id=(select id from entities where slug='reyes-sastres-sevilla') and mp.band_entity_id=(select id from entities where slug='las-cigarreras') and mp.year_to=2025 and not exists (select 1 from source_links x where x.source_id=s.id and x.music_accompaniment_period_id=mp.id and x.scope='Acompañamiento histórico · 2024-2025');
insert into source_links (source_id,entity_id,scope,notes) select s.id,e.id,'Patrimonio · orfebrería','Coronas históricas.' from sources s,entities e where s.url='https://www.artesacro.org/Noticia/Ver/17370/hoy-salida-procesional-ntra-sra-reyes-patrona-sastres' and e.slug='coronas-reyes-sastres' and not exists (select 1 from source_links x where x.source_id=s.id and x.entity_id=e.id and x.scope='Patrimonio · orfebrería');
insert into source_links (source_id,entity_id,scope,notes) select s.id,e.id,'Patrimonio · bordado','Techo culminado en 2024.' from sources s,entities e where s.url='https://www.artesacro.org/Noticia/Ver/157773/virgen-reyes-sastres-realizo-ayer-su-anual-procesion' and e.slug='techo-tumbilla-reyes-sastres' and not exists (select 1 from source_links x where x.source_id=s.id and x.entity_id=e.id and x.scope='Patrimonio · bordado');
insert into source_links (source_id,entity_id,scope,notes) select s.id,e.id,'Acontecimiento · constancia 1252','Respaldo parroquial.' from sources s,entities e where s.url='https://parroquiasanildefonso.wordpress.com/nuestra-senora-de-los-reyes/' and e.slug='sastres-constancia-documental-1252' and not exists (select 1 from source_links x where x.source_id=s.id and x.entity_id=e.id and x.scope='Acontecimiento · constancia 1252');
insert into source_links (source_id,entity_id,scope,notes) select s.id,e.id,'Acontecimiento · sede 1840','Respaldo parroquial.' from sources s,entities e where s.url='https://parroquiasanildefonso.wordpress.com/nuestra-senora-de-los-reyes/' and e.slug='sastres-san-ildefonso-1840' and not exists (select 1 from source_links x where x.source_id=s.id and x.entity_id=e.id and x.scope='Acontecimiento · sede 1840');
insert into source_links (source_id,entity_id,scope,notes) select s.id,e.id,'Acontecimiento · recuperación 2003','Procesión recuperada en 2003.' from sources s,entities e where s.url='https://www.artesacro.org/Noticia/Ver/157773/virgen-reyes-sastres-realizo-ayer-su-anual-procesion' and e.slug='sastres-recuperacion-procesion-2003' and not exists (select 1 from source_links x where x.source_id=s.id and x.entity_id=e.id and x.scope='Acontecimiento · recuperación 2003');